Enh deloy release v6
OctopusDeploy/OctoTFS pull request #278
Opened 2023-01-12 07:10 UTC by benPearce1

2023-01-12 23:58 UTC, benPearce1 commented on pack.ps1
> +    & npm uninstall tfx-cli
This is the only change to this line, the rest was auto-formatting kicking in

2023-01-13 00:00 UTC, benPearce1 commented on source/tasks/Deploy/DeployV6/input-parameters.test.ts
> +export class MockTaskWrapper implements TaskWrapper {
This needs to move to a common location, but I initially had a reference issue so I put it here for now

2023-01-13 00:13 UTC, benPearce1 commented on source/tasks/Deploy/DeployV6/task.json
> +            "helpMarkDown": "Additional arguments are no longer supported, move these values to the appropriate fields",
Wording?

2023-01-13 00:13 UTC, benPearce1 commented on source/tasks/Deploy/DeployV6/task.json
> +        "Node16": {
updated

2023-01-13 00:14 UTC, benPearce1 commented on source/tasks/Utils/command-line-args.test.ts
> +describe("cli args", () => {
These tests were me working out how to parse the arguments from the `AdditionalArguments` field, thought I would leave them here for future reference

2023-01-13 01:12 UTC, slewis74 commented on source/tasks/Deploy/DeployV6/task.json
> +        "Node16": {
👍

2023-01-13 01:27 UTC, slewis74 requested changes
Looking good. Offered some ideas on the wording for the no longer supported fields. `vsts.md` hasn't been updated.

2023-01-13 01:27 UTC, slewis74 commented on source/tasks/Deploy/DeployV6/task.json
> +            "helpMarkDown": "List of environments to deploy to, one environment per line"
```suggestion
            "helpMarkDown": "List of environments to deploy to, one environment per line. (Note: multiple on a line, separated by commas, is supported to ease migration from earlier versions of the step but this format should be considered deprecated)"
```

2023-01-13 01:27 UTC, slewis74 commented on source/tasks/Deploy/DeployV6/task.json
> +            "helpMarkDown": "Additional arguments are no longer supported, move these values to the appropriate fields",
```suggestion
            "helpMarkDown": "Additional arguments are no longer supported. This field has been retained to ease migration from earlier versions of the step but values should be moved to the appropriate fields.",
```

2023-01-16 05:12 UTC, slewis74 approved these changes

2023-01-16 05:52 UTC, merged